security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
ccd:
  host: ${ORDS_HOST}
  generic-agen-id:  ${GENERIC_AGENCY_ID}
  generic-part-id:  ${GENERIC_PART_ID}
  adobe-host: ${ADOBE_HOST}
  report-app-name: ${REPORT_APP_NAME}


management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

