security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

test:
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  api-host: ${API_HOST}
  api-host-secure: ${API_HOST_SECURE}
server:
  port: 8081
