# Deploy an artifact onto Test
name: Promote jag-ccd and jag-ccd-tests to Prod
on:
  workflow_dispatch:
    inputs:
      application:
        required: true
        description: What application you want to promote?
        type: choice
        options:
          - jag-ccd
          - jag-ccd-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.CCD_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.CCD_ARTIFACTORY_PASSWORD }}

      - name: Docker Pull Dev Image from Artifactory
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker pull artifacts.developer.gov.bc.ca/c52e-${{ github.event.inputs.application }}/${{ github.event.inputs.application }}:test
          docker tag artifacts.developer.gov.bc.ca/c52e-${{ github.event.inputs.application }}/${{ github.event.inputs.application }}:test artifacts.developer.gov.bc.ca/c52e-${{ github.event.inputs.application }}/${{ github.event.inputs.application }}:prod
      
      - name: Docker Push Test Image To Artifactory
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker push artifacts.developer.gov.bc.ca/c52e-${{ github.event.inputs.application }}/${{ github.event.inputs.application }}:prod

      # Get SHORT_SHA for the version
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Checkout ArgoCD Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov-c/tenant-gitops-52e74e
          ref: test
          token: ${{ secrets.ARGO_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: gitops

      - name: Update ADMIN Helm Values and Commit
        id: helm-admin
        if: ${{ github.event.inputs.application == 'jag-ccd-tests' }}
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/ccdtesttag: .*/ccdtesttag: test # Image Updated on $DATETIME/" ../deploy/test_values.yaml
          sed -i "s/appVersion: .*/appVersion: ${{ env.releaseVersion }}.${{ env.gitsha }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add .
          
          git add ../deploy/test_values.yaml
          
          # Repackage Helm Chart      

          cd ccd-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Test AI Reviewer Admin image tag"
          git push origin test  # Update the branch name as needed
      
      - name: Update API Helm Values and Commit
        id: helm-api
        if: ${{ github.event.inputs.application == 'jag-ccd' }}
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/ccdtag: .*/ccdtag: test # Image Updated on $DATETIME/" ../deploy/test_values.yaml
          sed -i "s/appVersion: .*/appVersion: ${{ env.releaseVersion }}.${{ env.gitsha }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add .
          
          git add ../deploy/test_values.yaml
          
          # Repackage Helm Chart      

          cd ccd-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Test AI Reviewer API image tag"
          git push origin test  # Update the branch name as needed