name: ZAP Scanner for CCD APIs
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update zap properties file
        run: echo  "replacer.full_list(0).replacement=${{ secrets.BASIC_AUTH_HEADER_UNSECURE_DEV }}" >> "$GITHUB_WORKSPACE/zapoptions.prop"
      
      - name: ZAP Scan - CCDUserMapping API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - CCDUserMapping API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.CCDUserMapping.ws:ccdUserMapping?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - CivilFileContent API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - CivilFileContent API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.CivilFileContent.ws:CivilFileContent?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - CodeValues API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - CodeValues API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.CodeValues.ws.provider:CodeValues?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - CourtList API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - CourtList API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.CourtLists.ws.provider:CourtList?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - CriminalFileContent API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - CriminalFileContent API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.CriminalFileContent.ws.provider:CriminalFileContent?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - GetROPReport API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - GetROPReport API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.GetROPReport.ws:GetROPReport?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - GetUserLogin API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - GetUserLogin API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.GetUserLogin.WS:getUserLogin?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - ProcessResults API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - ProcessResults API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.ProcessResults.ws.provider:ProcessResults?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - GetDocument API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - GetDocument API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.GetDocument.ws:GetDocument?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - DevUtil API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - DevUtil API'
          target: '${{ secrets.JAG_CCD_RouteUrl }}/ws/CCD.Source.DevUtil.ws:DevUtils?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
